repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: samples/
  - repo: https://github.com/timothycrosley/isort
    rev: v5.11.3
    hooks:
      - id: isort
  - repo: https://github.com/guilatrova/tryceratops
    rev: v1.1.0
    hooks:
      - id: tryceratops
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "poetry run mypy"
        language: system
        types: [python]
        # use require_serial so that script is only called once per commit
        require_serial: true
        # print the number of files as a sanity-check
        verbose: true
