repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        language: system
        types: [python]
        entry: "poetry run pyright"
        require_serial: true  # use require_serial so that script is only called once per commit
        verbose: true  # print the number of files as a sanity-check
