"""Self-contained static HTML renderer for the gracy doc model.

render(doc) turns an ApiDoc (see gracy.docs._model) into ONE deterministic
HTML page: no CDN, no external assets, vanilla inline CSS and a tiny inline
script (theme toggle + copy buttons only). Stdlib-only.
"""

from __future__ import annotations

import html as _html
import json
import re
import typing as t

from gracy.docs._model import ApiDoc, ConfigSummary, EndpointDoc, EndpointGroup, ParamDoc, StatusOutcome

__all__ = ["render", "render_html"]


# --------------------------------------------------------------------------- helpers


def _esc(value: t.Any) -> str:
    return _html.escape(str(value), quote=True)


_PLACEHOLDER = re.compile(r"\{([^{}/]+)\}")


def _path_html(path: str) -> str:
    """Escape a path and wrap {placeholders} in a highlight span."""
    return _PLACEHOLDER.sub(r'<span class="ph">{\1}</span>', _esc(path))


def _anchor(group: EndpointGroup, ep: EndpointDoc) -> str:
    return f"op-{group.name}-{ep.name}" if group.name else f"op-{ep.name}"


_EXAMPLES = {
    "str": '"example"',
    "int": "0",
    "float": "0.0",
    "bool": "True",
    "bytes": 'b"example"',
    "dict": "{}",
    "list": "[]",
    "tuple": "()",
    "set": "set()",
    "None": "None",
    "Any": "...",
}


def _example_value(param: ParamDoc) -> str:
    if param.default_repr is not None:
        return param.default_repr
    base = param.type_repr.split("|", 1)[0].strip()
    base = base.split("[", 1)[0].strip()
    return _EXAMPLES.get(base, "...")


def _usage_snippet(doc: ApiDoc, group: EndpointGroup, ep: EndpointDoc) -> str:
    args = ", ".join(f"{p.name}={_example_value(p)}" for p in ep.params if p.required)
    target = f"api.{group.name}.{ep.name}" if group.name else f"api.{ep.name}"
    return f"async with {doc.name}() as api:\n    result = await {target}({args})"


def _status_class(status: int | str) -> str:
    if isinstance(status, int):
        family = status // 100
        if family == 2:
            return "s2"
        if family == 3:
            return "s3"
        if family == 4:
            return "s4"
        if family == 5:
            return "s5"
    return "sd"


# --------------------------------------------------------------------------- fragments


def _sidebar(doc: ApiDoc) -> str:
    out: list[str] = ['<aside class="sidebar">']
    out.append('<div class="brand">')
    out.append(f'<div class="brand-title">{_esc(doc.title)}</div>')
    out.append(f'<span class="version-badge">v{_esc(doc.version)}</span>')
    out.append("</div>")
    out.append(f'<code class="base-url">{_esc(doc.base_url)}</code>')
    out.append("<nav>")
    for group in doc.groups:
        label = group.name or "endpoints"
        out.append(f'<div class="nav-group">{_esc(label)}</div>')
        for ep in group.endpoints:
            method = ep.http_method.lower()
            out.append(
                f'<a class="nav-link" href="#{_anchor(group, ep)}">'
                f'<span class="chip chip-sm method-{_esc(method)}">{_esc(ep.http_method)}</span>'
                f"<span>{_esc(ep.name)}</span></a>"
            )
    out.append("</nav>")
    out.append('<div class="sidebar-foot">generated by gracy</div>')
    out.append("</aside>")
    return "\n".join(out)


def _policies_card(summary: ConfigSummary) -> str:
    rows: list[tuple[str, str]] = []
    if summary.retry:
        rows.append(("Retry", summary.retry))
    for rule in summary.throttle:
        rows.append(("Throttle", rule))
    if summary.concurrency:
        rows.append(("Concurrency", summary.concurrency))
    if summary.queue:
        rows.append(("Queue", summary.queue))
    if summary.decoder:
        rows.append(("Decoder", summary.decoder))

    out: list[str] = ['<section class="card policies">', "<h2>Client policies</h2>"]
    if rows:
        out.append('<dl class="policy-rows">')
        for label, value in rows:
            out.append(f"<div><dt>{_esc(label)}</dt><dd>{_esc(value)}</dd></div>")
        out.append("</dl>")
    else:
        out.append('<p class="muted">No client-wide policies configured — gracy defaults apply.</p>')
    out.append("</section>")
    return "\n".join(out)


def _params_table(params: list[ParamDoc]) -> str:
    if not params:
        return '<p class="muted">No parameters.</p>'
    out: list[str] = ['<div class="tablewrap"><table class="params">']
    out.append("<thead><tr><th>Name</th><th>In</th><th>Type</th><th>Required</th><th>Default</th></tr></thead>")
    out.append("<tbody>")
    for p in params:
        required = '<span class="req-dot" title="required"></span>' if p.required else '<span class="muted">—</span>'
        default = f"<code>{_esc(p.default_repr)}</code>" if p.default_repr is not None else '<span class="muted">—</span>'
        out.append(
            "<tr>"
            f"<td><code>{_esc(p.name)}</code></td>"
            f'<td><span class="kind kind-{_esc(p.kind)}">{_esc(p.kind)}</span></td>'
            f"<td><code>{_esc(p.type_repr)}</code></td>"
            f"<td>{required}</td>"
            f"<td>{default}</td>"
            "</tr>"
        )
    out.append("</tbody></table></div>")
    return "\n".join(out)


def _responses(ep: EndpointDoc) -> str:
    rows: list[StatusOutcome] = []
    has_success = any(isinstance(o.status, int) and 200 <= o.status < 300 for o in ep.status_map)
    if not has_success:
        rows.append(StatusOutcome(200, f"returns {ep.returns.type_repr}"))
    rows.extend(ep.status_map)

    out: list[str] = ['<ul class="responses">']
    for outcome in rows:
        detail = f'<span class="detail">{_esc(outcome.detail)}</span>' if outcome.detail else ""
        out.append(
            "<li>"
            f'<span class="status {_status_class(outcome.status)}">{_esc(outcome.status)}</span>'
            f'<span class="outcome">{_esc(outcome.outcome)}</span>{detail}'
            "</li>"
        )
    out.append("</ul>")
    return "\n".join(out)


def _schema_details(ep: EndpointDoc) -> str:
    schema = ep.returns.json_schema
    if schema is None:
        return ""
    pretty = json.dumps(schema, indent=2)
    label = ep.returns.type_repr.replace(" | None", "")
    return (
        '<details class="schema">'
        f"<summary>JSON Schema — <code>{_esc(label)}</code></summary>"
        f"<pre><code>{_esc(pretty)}</code></pre>"
        "</details>"
    )


def _endpoint_card(doc: ApiDoc, group: EndpointGroup, ep: EndpointDoc) -> str:
    anchor = _anchor(group, ep)
    method = ep.http_method.lower()
    out: list[str] = [f'<article class="card endpoint" id="{_esc(anchor)}">']

    out.append('<header class="ep-head">')
    out.append(f'<h3 class="ep-name">{_esc(ep.name)}<a class="anchor" href="#{_esc(anchor)}">#</a></h3>')
    out.append('<div class="ep-route">')
    out.append(f'<span class="chip method-{_esc(method)}">{_esc(ep.http_method)}</span>')
    out.append(f'<code class="path">{_path_html(ep.path)}</code>')
    out.append(f'<button class="copy" type="button" data-copy="{_esc(ep.path)}" title="Copy path">copy</button>')
    out.append("</div>")
    out.append("</header>")

    if ep.summary:
        out.append(f'<p class="summary">{_esc(ep.summary)}</p>')
    if ep.description:
        out.append(f'<p class="desc">{_esc(ep.description)}</p>')

    if ep.config_notes:
        out.append('<div class="notes">')
        for note in ep.config_notes:
            out.append(f'<span class="note">{_esc(note)}</span>')
        out.append("</div>")

    out.append("<h4>Parameters</h4>")
    out.append(_params_table(ep.params))

    out.append("<h4>Responses</h4>")
    out.append(_responses(ep))
    optional_note = ' <span class="muted">(optional)</span>' if ep.returns.is_optional else ""
    out.append(f'<p class="returns">Returns <code>{_esc(ep.returns.type_repr)}</code>{optional_note}</p>')
    out.append(_schema_details(ep))

    out.append("<h4>Usage</h4>")
    snippet = _usage_snippet(doc, group, ep)
    out.append(
        '<div class="snippet">'
        '<button class="copy" type="button" data-copy-block title="Copy snippet">copy</button>'
        f"<pre><code>{_esc(snippet)}</code></pre>"
        "</div>"
    )

    out.append("</article>")
    return "\n".join(out)


def _main(doc: ApiDoc) -> str:
    out: list[str] = ['<main class="content">']
    out.append('<header class="page-head">')
    out.append("<div>")
    out.append(f"<h1>{_esc(doc.title)}</h1>")
    out.append(
        f'<p class="page-meta"><span class="version-badge">v{_esc(doc.version)}</span> '
        f"<code>{_esc(doc.base_url)}</code></p>"
    )
    out.append("</div>")
    out.append('<button class="theme-toggle" type="button" id="theme-toggle" title="Toggle theme">◐ theme</button>')
    out.append("</header>")
    if doc.description:
        out.append(f'<p class="page-desc">{_esc(doc.description)}</p>')

    out.append(_policies_card(doc.config_summary))

    for group in doc.groups:
        if group.name:
            prefix = f' <code class="prefix">{_esc(group.path_prefix)}</code>' if group.path_prefix else ""
            out.append(f'<h2 class="group-title">{_esc(group.name)}{prefix}</h2>')
        else:
            out.append('<h2 class="group-title">Endpoints</h2>')
        for ep in group.endpoints:
            out.append(_endpoint_card(doc, group, ep))

    out.append('<footer class="page-foot">generated by gracy — your class is the spec</footer>')
    out.append("</main>")
    return "\n".join(out)


# --------------------------------------------------------------------------- theme

_LIGHT_VARS = """\
  --bg: #f6f7f9;
  --panel: #ffffff;
  --text: #1c2433;
  --muted: #647080;
  --border: #e2e6ec;
  --code-bg: #eef1f5;
  --accent: #4f6df5;
  --shadow: 0 1px 2px rgba(16, 24, 40, 0.06);
  --status-2xx-bg: #e3f4ec; --status-2xx-fg: #0b7350;
  --status-3xx-bg: #e7edf7; --status-3xx-fg: #33518f;
  --status-4xx-bg: #fdf0e0; --status-4xx-fg: #a05a08;
  --status-5xx-bg: #fbe8e8; --status-5xx-fg: #b02a2a;
  --status-def-bg: #edeff2; --status-def-fg: #5b6472;\
"""

_DARK_VARS = """\
  --bg: #10141b;
  --panel: #181e28;
  --text: #e5eaf2;
  --muted: #8b96a8;
  --border: #29323f;
  --code-bg: #212936;
  --accent: #7c93ff;
  --shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
  --status-2xx-bg: #14352a; --status-2xx-fg: #5fd3a5;
  --status-3xx-bg: #1c2940; --status-3xx-fg: #8fabe8;
  --status-4xx-bg: #3a2b12; --status-4xx-fg: #e8b364;
  --status-5xx-bg: #3d1c1c; --status-5xx-fg: #ef8f8f;
  --status-def-bg: #242b36; --status-def-fg: #98a2b3;\
"""

_CSS = f"""\
:root {{
{_LIGHT_VARS}
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{_DARK_VARS}
  }}
}}
:root[data-theme="dark"] {{
{_DARK_VARS}
}}
* {{ box-sizing: border-box; }}
html {{ scroll-behavior: smooth; }}
body {{
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}}
code, pre, .path, .base-url {{
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
  font-size: 0.92em;
}}
code {{ background: var(--code-bg); border-radius: 4px; padding: 0.1em 0.35em; }}
pre {{ margin: 0; overflow-x: auto; }}
pre code {{ background: none; padding: 0; }}
a {{ color: var(--accent); text-decoration: none; }}
.muted {{ color: var(--muted); }}

.layout {{ display: flex; min-height: 100vh; }}

/* ------------------------------------------------------------- sidebar */
.sidebar {{
  position: sticky; top: 0; align-self: flex-start;
  width: 264px; flex: none; height: 100vh; overflow-y: auto;
  padding: 20px 16px; border-right: 1px solid var(--border);
  display: flex; flex-direction: column; gap: 12px;
}}
.brand {{ display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }}
.brand-title {{ font-size: 17px; font-weight: 700; }}
.version-badge {{
  background: var(--code-bg); color: var(--muted); border: 1px solid var(--border);
  border-radius: 999px; padding: 0 8px; font-size: 12px; white-space: nowrap;
}}
.base-url {{ display: block; color: var(--muted); word-break: break-all; background: none; padding: 0; }}
nav {{ display: flex; flex-direction: column; gap: 2px; }}
.nav-group {{
  margin: 12px 0 4px; font-size: 11px; font-weight: 700; letter-spacing: 0.08em;
  text-transform: uppercase; color: var(--muted);
}}
.nav-link {{
  display: flex; align-items: center; gap: 8px; padding: 4px 8px;
  border-radius: 6px; color: var(--text); font-size: 14px;
}}
.nav-link:hover {{ background: var(--code-bg); }}
.sidebar-foot {{ margin-top: auto; padding-top: 16px; font-size: 12px; color: var(--muted); }}

/* ------------------------------------------------------------- content */
.content {{ flex: 1; min-width: 0; max-width: 1100px; padding: 28px 36px 64px; }}
.page-head {{ display: flex; align-items: flex-start; justify-content: space-between; gap: 16px; }}
.page-head h1 {{ margin: 0 0 6px; font-size: 28px; }}
.page-meta {{ margin: 0; display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }}
.page-desc {{ color: var(--muted); max-width: 72ch; white-space: pre-line; }}
.theme-toggle {{
  flex: none; background: var(--panel); color: var(--text); border: 1px solid var(--border);
  border-radius: 8px; padding: 6px 12px; cursor: pointer; font: inherit; font-size: 13px;
}}
.theme-toggle:hover {{ border-color: var(--accent); }}
.group-title {{ margin: 36px 0 12px; font-size: 20px; }}
.group-title .prefix {{ font-size: 14px; color: var(--muted); }}
.page-foot {{ margin-top: 48px; font-size: 13px; color: var(--muted); }}

/* ------------------------------------------------------------- cards */
.card {{
  background: var(--panel); border: 1px solid var(--border); border-radius: 10px;
  box-shadow: var(--shadow); padding: 20px 22px; margin: 16px 0;
}}
.card h2 {{ margin: 0 0 12px; font-size: 17px; }}
.card h4 {{
  margin: 20px 0 8px; font-size: 12px; font-weight: 700;
  letter-spacing: 0.08em; text-transform: uppercase; color: var(--muted);
}}
.policy-rows {{ margin: 0; display: grid; gap: 8px; }}
.policy-rows > div {{ display: flex; gap: 12px; }}
.policy-rows dt {{ flex: none; width: 110px; font-weight: 600; color: var(--muted); }}
.policy-rows dd {{ margin: 0; }}

/* ------------------------------------------------------------- endpoint */
.ep-head {{ display: flex; flex-direction: column; gap: 10px; }}
.ep-name {{ margin: 0; font-size: 17px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }}
.anchor {{ margin-left: 8px; opacity: 0; font-weight: 400; }}
.endpoint:hover .anchor, .anchor:focus {{ opacity: 1; }}
.ep-route {{ display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }}
.path {{ background: var(--code-bg); border-radius: 6px; padding: 4px 10px; overflow-x: auto; max-width: 100%; }}
.ph {{ color: var(--accent); font-weight: 600; }}

.chip {{
  display: inline-block; border-radius: 5px; padding: 2px 9px; font-size: 12px;
  font-weight: 700; letter-spacing: 0.04em; color: #fff; line-height: 1.5;
}}
.chip-sm {{ padding: 0 5px; font-size: 10px; min-width: 34px; text-align: center; }}
.method-get {{ background: #0e8a5f; }}
.method-post {{ background: #2563eb; }}
.method-put {{ background: #d97706; }}
.method-patch {{ background: #7c3aed; }}
.method-delete {{ background: #dc2626; }}
.method-head, .method-options {{ background: #647080; }}

.summary {{ margin: 12px 0 0; font-weight: 600; }}
.desc {{ margin: 6px 0 0; color: var(--muted); white-space: pre-line; }}
.notes {{ margin-top: 12px; display: flex; gap: 6px; flex-wrap: wrap; }}
.note {{
  font-size: 12px; background: var(--code-bg); color: var(--muted);
  border: 1px solid var(--border); border-radius: 999px; padding: 1px 9px;
}}

.tablewrap {{ overflow-x: auto; }}
table.params {{ border-collapse: collapse; width: 100%; font-size: 14px; }}
table.params th {{
  text-align: left; font-size: 12px; color: var(--muted); font-weight: 600;
  padding: 6px 12px 6px 0; border-bottom: 1px solid var(--border);
}}
table.params td {{ padding: 7px 12px 7px 0; border-bottom: 1px solid var(--border); vertical-align: top; }}
table.params tr:last-child td {{ border-bottom: none; }}
.kind {{ font-size: 12px; color: var(--muted); }}
.req-dot {{
  display: inline-block; width: 8px; height: 8px; border-radius: 50%;
  background: var(--accent);
}}

.responses {{ list-style: none; margin: 0; padding: 0; display: grid; gap: 6px; }}
.responses li {{ display: flex; align-items: baseline; gap: 10px; flex-wrap: wrap; }}
.status {{
  flex: none; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px; font-weight: 700; border-radius: 5px; padding: 1px 8px; min-width: 52px; text-align: center;
}}
.status.s2 {{ background: var(--status-2xx-bg); color: var(--status-2xx-fg); }}
.status.s3 {{ background: var(--status-3xx-bg); color: var(--status-3xx-fg); }}
.status.s4 {{ background: var(--status-4xx-bg); color: var(--status-4xx-fg); }}
.status.s5 {{ background: var(--status-5xx-bg); color: var(--status-5xx-fg); }}
.status.sd {{ background: var(--status-def-bg); color: var(--status-def-fg); }}
.detail {{ color: var(--muted); font-size: 13px; }}
.returns {{ margin: 12px 0 0; }}

details.schema {{ margin-top: 10px; border: 1px solid var(--border); border-radius: 8px; }}
details.schema summary {{ cursor: pointer; padding: 8px 12px; font-size: 14px; color: var(--muted); }}
details.schema[open] summary {{ border-bottom: 1px solid var(--border); }}
details.schema pre {{ padding: 12px; }}

.snippet {{ position: relative; background: var(--code-bg); border-radius: 8px; padding: 12px 14px; }}
.copy {{
  background: var(--panel); color: var(--muted); border: 1px solid var(--border);
  border-radius: 6px; padding: 2px 9px; font: inherit; font-size: 12px; cursor: pointer;
}}
.copy:hover {{ color: var(--text); border-color: var(--accent); }}
.copy.copied {{ color: var(--status-2xx-fg); border-color: var(--status-2xx-fg); }}
.copy.copied::after {{ content: " \\2713"; }}
.snippet .copy {{ position: absolute; top: 8px; right: 8px; }}

/* ------------------------------------------------------------- responsive + print */
@media (max-width: 860px) {{
  .layout {{ flex-direction: column; }}
  .sidebar {{ position: static; width: auto; height: auto; border-right: none; border-bottom: 1px solid var(--border); }}
  .content {{ padding: 20px 16px 48px; }}
}}
@media print {{
  .sidebar, .theme-toggle, .copy {{ display: none; }}
  .card {{ box-shadow: none; break-inside: avoid; }}
  body {{ background: #fff; }}
}}\
"""

_JS = """\
(function () {
  "use strict";
  var toggle = document.getElementById("theme-toggle");
  if (toggle) {
    toggle.addEventListener("click", function () {
      var root = document.documentElement;
      var prefersDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
      var current = root.getAttribute("data-theme") || (prefersDark ? "dark" : "light");
      root.setAttribute("data-theme", current === "dark" ? "light" : "dark");
    });
  }
  Array.prototype.forEach.call(document.querySelectorAll(".copy"), function (el) {
    el.addEventListener("click", function () {
      var text;
      if (el.hasAttribute("data-copy")) {
        text = el.getAttribute("data-copy");
      } else {
        var block = el.closest(".snippet");
        var pre = block && block.querySelector("pre");
        text = pre ? pre.textContent : "";
      }
      var done = function () {
        el.classList.add("copied");
        setTimeout(function () { el.classList.remove("copied"); }, 1200);
      };
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(done, done);
      } else {
        done();
      }
    });
  });
})();\
"""


# --------------------------------------------------------------------------- entry point


def render(doc: ApiDoc) -> str:
    """Render an ApiDoc into a single self-contained, deterministic HTML page."""
    parts: list[str] = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{_esc(doc.title)} — API docs</title>",
        f"<style>\n{_CSS}\n</style>",
        "</head>",
        "<body>",
        '<div class="layout">',
        _sidebar(doc),
        _main(doc),
        "</div>",
        f"<script>\n{_JS}\n</script>",
        "</body>",
        "</html>",
    ]
    return "\n".join(parts) + "\n"


render_html = render  # what gracy.docs.to_html imports
