"""Self-contained static HTML renderer for the gracy doc model.

render(doc) turns an ApiDoc (see gracy.docs._model) into ONE deterministic
HTML page: no CDN, no external assets, vanilla inline CSS and a tiny inline
script (theme toggle + copy buttons only). Stdlib-only.
"""

from __future__ import annotations

import html as _html
import json
import re
import typing as t

from gracy.docs._model import ApiDoc, ConfigSummary, EndpointDoc, EndpointGroup, ParamDoc, StatusOutcome
from gracy.docs._styles import _CSS, _DARK_VARS, _JS, _LIGHT_VARS  # noqa: F401  (re-exported for compatibility)

__all__ = ["render", "render_html"]


# --------------------------------------------------------------------------- helpers


def _esc(value: t.Any) -> str:
    return _html.escape(str(value), quote=True)


_PLACEHOLDER = re.compile(r"\{([^{}/]+)\}")


def _path_html(path: str) -> str:
    """Escape a path and wrap {placeholders} in a highlight span."""
    return _PLACEHOLDER.sub(r'<span class="ph">{\1}</span>', _esc(path))


def _anchor(group: EndpointGroup, ep: EndpointDoc) -> str:
    return f"op-{group.name}-{ep.name}" if group.name else f"op-{ep.name}"


_EXAMPLES = {
    "str": '"example"',
    "int": "0",
    "float": "0.0",
    "bool": "True",
    "bytes": 'b"example"',
    "dict": "{}",
    "list": "[]",
    "tuple": "()",
    "set": "set()",
    "None": "None",
    "Any": "...",
}


def _example_value(param: ParamDoc) -> str:
    if param.default_repr is not None:
        return param.default_repr
    base = param.type_repr.split("|", 1)[0].strip()
    base = base.split("[", 1)[0].strip()
    return _EXAMPLES.get(base, "...")


def _usage_snippet(doc: ApiDoc, group: EndpointGroup, ep: EndpointDoc) -> str:
    args = ", ".join(f"{p.name}={_example_value(p)}" for p in ep.params if p.required)
    target = f"api.{group.name}.{ep.name}" if group.name else f"api.{ep.name}"
    return f"async with {doc.name}() as api:\n    result = await {target}({args})"


def _status_class(status: int | str) -> str:
    if isinstance(status, int):
        family = status // 100
        if family == 2:
            return "s2"
        if family == 3:
            return "s3"
        if family == 4:
            return "s4"
        if family == 5:
            return "s5"
    return "sd"


# --------------------------------------------------------------------------- fragments


def _sidebar(doc: ApiDoc) -> str:
    out: list[str] = ['<aside class="sidebar">']
    out.append('<div class="brand">')
    out.append(f'<div class="brand-title">{_esc(doc.title)}</div>')
    out.append(f'<span class="version-badge">v{_esc(doc.version)}</span>')
    out.append("</div>")
    out.append(f'<code class="base-url">{_esc(doc.base_url)}</code>')
    out.append("<nav>")
    for group in doc.groups:
        label = group.name or "endpoints"
        out.append(f'<div class="nav-group">{_esc(label)}</div>')
        for ep in group.endpoints:
            method = ep.http_method.lower()
            out.append(
                f'<a class="nav-link" href="#{_anchor(group, ep)}">'
                f'<span class="chip chip-sm method-{_esc(method)}">{_esc(ep.http_method)}</span>'
                f"<span>{_esc(ep.name)}</span></a>"
            )
    out.append("</nav>")
    out.append('<div class="sidebar-foot">generated by gracy</div>')
    out.append("</aside>")
    return "\n".join(out)


def _policies_card(summary: ConfigSummary) -> str:
    rows: list[tuple[str, str]] = []
    if summary.retry:
        rows.append(("Retry", summary.retry))
    for rule in summary.throttle:
        rows.append(("Throttle", rule))
    if summary.concurrency:
        rows.append(("Concurrency", summary.concurrency))
    if summary.queue:
        rows.append(("Queue", summary.queue))
    if summary.decoder:
        rows.append(("Decoder", summary.decoder))

    out: list[str] = ['<section class="card policies">', "<h2>Client policies</h2>"]
    if rows:
        out.append('<dl class="policy-rows">')
        for label, value in rows:
            out.append(f"<div><dt>{_esc(label)}</dt><dd>{_esc(value)}</dd></div>")
        out.append("</dl>")
    else:
        out.append('<p class="muted">No client-wide policies configured - gracy defaults apply.</p>')
    out.append("</section>")
    return "\n".join(out)


def _params_table(params: list[ParamDoc]) -> str:
    if not params:
        return '<p class="muted">No parameters.</p>'
    out: list[str] = ['<div class="tablewrap"><table class="params">']
    out.append("<thead><tr><th>Name</th><th>In</th><th>Type</th><th>Required</th><th>Default</th></tr></thead>")
    out.append("<tbody>")
    for p in params:
        required = '<span class="req-dot" title="required"></span>' if p.required else '<span class="muted">-</span>'
        default = f"<code>{_esc(p.default_repr)}</code>" if p.default_repr is not None else '<span class="muted">-</span>'
        out.append(
            "<tr>"
            f"<td><code>{_esc(p.name)}</code></td>"
            f'<td><span class="kind kind-{_esc(p.kind)}">{_esc(p.kind)}</span></td>'
            f"<td><code>{_esc(p.type_repr)}</code></td>"
            f"<td>{required}</td>"
            f"<td>{default}</td>"
            "</tr>"
        )
    out.append("</tbody></table></div>")
    return "\n".join(out)


def _responses(ep: EndpointDoc) -> str:
    rows: list[StatusOutcome] = []
    has_success = any(isinstance(o.status, int) and 200 <= o.status < 300 for o in ep.status_map)
    if not has_success:
        rows.append(StatusOutcome(200, f"returns {ep.returns.type_repr}"))
    rows.extend(ep.status_map)

    out: list[str] = ['<ul class="responses">']
    for outcome in rows:
        detail = f'<span class="detail">{_esc(outcome.detail)}</span>' if outcome.detail else ""
        out.append(
            "<li>"
            f'<span class="status {_status_class(outcome.status)}">{_esc(outcome.status)}</span>'
            f'<span class="outcome">{_esc(outcome.outcome)}</span>{detail}'
            "</li>"
        )
    out.append("</ul>")
    return "\n".join(out)


def _schema_details(ep: EndpointDoc) -> str:
    schema = ep.returns.json_schema
    if schema is None:
        return ""
    pretty = json.dumps(schema, indent=2)
    label = ep.returns.type_repr.replace(" | None", "")
    return (
        '<details class="schema">'
        f"<summary>JSON Schema - <code>{_esc(label)}</code></summary>"
        f"<pre><code>{_esc(pretty)}</code></pre>"
        "</details>"
    )


def _endpoint_card(doc: ApiDoc, group: EndpointGroup, ep: EndpointDoc) -> str:
    anchor = _anchor(group, ep)
    method = ep.http_method.lower()
    out: list[str] = [f'<article class="card endpoint" id="{_esc(anchor)}">']

    out.append('<header class="ep-head">')
    out.append(f'<h3 class="ep-name">{_esc(ep.name)}<a class="anchor" href="#{_esc(anchor)}">#</a></h3>')
    out.append('<div class="ep-route">')
    out.append(f'<span class="chip method-{_esc(method)}">{_esc(ep.http_method)}</span>')
    out.append(f'<code class="path">{_path_html(ep.path)}</code>')
    out.append(f'<button class="copy" type="button" data-copy="{_esc(ep.path)}" title="Copy path">copy</button>')
    out.append("</div>")
    out.append("</header>")

    if ep.summary:
        out.append(f'<p class="summary">{_esc(ep.summary)}</p>')
    if ep.description:
        out.append(f'<p class="desc">{_esc(ep.description)}</p>')

    if ep.config_notes:
        out.append('<div class="notes">')
        for note in ep.config_notes:
            out.append(f'<span class="note">{_esc(note)}</span>')
        out.append("</div>")

    out.append("<h4>Parameters</h4>")
    out.append(_params_table(ep.params))

    out.append("<h4>Responses</h4>")
    out.append(_responses(ep))
    optional_note = ' <span class="muted">(optional)</span>' if ep.returns.is_optional else ""
    out.append(f'<p class="returns">Returns <code>{_esc(ep.returns.type_repr)}</code>{optional_note}</p>')
    out.append(_schema_details(ep))

    out.append("<h4>Usage</h4>")
    snippet = _usage_snippet(doc, group, ep)
    out.append(
        '<div class="snippet">'
        '<button class="copy" type="button" data-copy-block title="Copy snippet">copy</button>'
        f"<pre><code>{_esc(snippet)}</code></pre>"
        "</div>"
    )

    out.append("</article>")
    return "\n".join(out)


def _main(doc: ApiDoc) -> str:
    out: list[str] = ['<main class="content">']
    out.append('<header class="page-head">')
    out.append("<div>")
    out.append(f"<h1>{_esc(doc.title)}</h1>")
    out.append(
        f'<p class="page-meta"><span class="version-badge">v{_esc(doc.version)}</span> '
        f"<code>{_esc(doc.base_url)}</code></p>"
    )
    out.append("</div>")
    out.append('<button class="theme-toggle" type="button" id="theme-toggle" title="Toggle theme">◐ theme</button>')
    out.append("</header>")
    if doc.description:
        out.append(f'<p class="page-desc">{_esc(doc.description)}</p>')

    out.append(_policies_card(doc.config_summary))

    for group in doc.groups:
        if group.name:
            prefix = f' <code class="prefix">{_esc(group.path_prefix)}</code>' if group.path_prefix else ""
            out.append(f'<h2 class="group-title">{_esc(group.name)}{prefix}</h2>')
        else:
            out.append('<h2 class="group-title">Endpoints</h2>')
        for ep in group.endpoints:
            out.append(_endpoint_card(doc, group, ep))

    out.append('<footer class="page-foot">generated by gracy - your class is the spec</footer>')
    out.append("</main>")
    return "\n".join(out)


# --------------------------------------------------------------------------- entry point


def render(doc: ApiDoc) -> str:
    """Render an ApiDoc into a single self-contained, deterministic HTML page."""
    parts: list[str] = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{_esc(doc.title)} - API docs</title>",
        f"<style>\n{_CSS}\n</style>",
        "</head>",
        "<body>",
        '<div class="layout">',
        _sidebar(doc),
        _main(doc),
        "</div>",
        f"<script>\n{_JS}\n</script>",
        "</body>",
        "</html>",
    ]
    return "\n".join(parts) + "\n"


render_html = render  # what gracy.docs.to_html imports
